name: Table of Contents

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

jobs:
  toc:
    name: Check interface versions
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Check for outdated interface versions
        run: .github/check-interface-versions.sh
